# docker-compose for debugging with vscode
# docker-compose -p hydroshare -f .vscode/docker-compose.debug.yml up
version: '3'
services:
  data.local.org:
    extends:
      file: ../local-dev.yml
      service: data.local.org
  users.local.org:
    extends:
      file: ../local-dev.yml
      service: users.local.org
  postgis:
    extends:
      file: ../local-dev.yml
      service: postgis
  rabbitmq:
    extends:
      file: ../local-dev.yml
      service: rabbitmq
  solr:
    extends:
      file: ../local-dev.yml
      service: solr
    volumes:
      - "..:/hydroshare"
      - "solr_data_vol:/opt/solr/server/solr"
  nginx:
    extends:
      file: ../local-dev.yml
      service: nginx
    build:
      context: ../nginx
      dockerfile: Dockerfile-nginx
  hydroshare:
    extends:
      file: ../local-dev.yml
      service: hydroshare
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      # hydroshare repository
      - "..:/hydroshare"
      # shared location for gunicorn.sock between containers
      - "temp_vol:/hs_tmp"
      # temp directory shared with celery workers
      - "share_vol:/shared_tmp"
    ports:
      - "1338:2022"
      - "8000:8000"
      - 5678:5678
    command: /bin/bash .vscode/init-hydroshare-debug
  defaultworker:
    extends:
      file: ../local-dev.yml
      service: defaultworker
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - "..:/hydroshare"

volumes:
  idata_iconf_vol:
  idata_vault_vol:
  idata_pgres_vol:
  iuser_iconf_vol:
  iuser_vault_vol:
  iuser_pgres_vol:
  postgis_data_vol:
  solr_data_vol:
  temp_vol:
  share_vol:
  rabbitmq_data_vol:
